import type { MetadataRoute } from "next";

/**
 * Makes the site installable to a phone home screen. Generated by Next rather
 * than hand-written into public/, so the values live with the code and ship on
 * push — no dashboard step.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Film Roulette",
    short_name: "Roulette",
    description:
      "Set your filters, roll once, and get one film or series to watch tonight.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#0b0e11",
    theme_color: "#0b0e11",
    categories: ["entertainment", "lifestyle"],
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
